version: '3.7'
networks:
  dspacenet:

services:

  # DSpace database container
  dspacedb:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    image:
      ibict/postgresdspace7
    container_name: bd_dspace7
    ports:
      - "5006:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
