version: '3.7'


services:

  dspace7db:
    build:
      context: ../postgres
      dockerfile: Dockerfile
    image:
      ibict/postgresdspace7
    container_name: dspace7db
    ports:
      - "127.0.0.1:8787:5432"
    environment:
      - POSTGRES_PASSWORD=xxxxx #Postgres password
      - TZ=America/Sao_Paulo
    networks:
      - dspacenet
  #    volumes:
  #      -  ../../postgres-data:/var/lib/postgresql/data

  dspace7:
    container_name: dspace7
    environment:
      dspace__P__dir: /dspace
      solr__P__server: http://dspace7solr:8983/solr
      TZ: 'America/Sao_Paulo'
      proxies__P__trusted__P__ipranges: '172.23.0'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dspacenet
    ports:
      - published: 8080 #Port for tomcat
        target: 8080
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Keep DSpace assetstore directory between reboots
      - ../../dspace-install-dir:/dspace
      - m2:/root/.m2
    entrypoint:
      - /bin/bash
      - '-c'
      - |
        rm -rf /dspace/config/spring
        rm -rf /dspace/lib
        rm -rf /dspace/webapps
        cp -r /dspace-tmp/* /dspace
        ls -lsah /dspace/webapps
        /dspace/bin/dspace database migrate ignored
        mkdir /dspace/config/temp
        cp /dspace/config/item-submission.xml /dspace/config/temp
        cp /dspace/config/input-forms.xml /dspace/config/temp
        rm /dspace/config/spring/api/bte.xml
        rm /dspace/config/GeoLiteCity.dat
        /dspace/bin/dspace submission-forms-migrate -s /dspace/config/temp/item-submission.xml -f /dspace/config/temp/input-forms.xml
        mv /dspace/config/item-submission.xml.migrated /dspace/config/item-submission.xml
        mv /dspace/config/submission-forms.xml.migrated /dspace/config/submission-forms.xml
        sed -i 's/<step id="collection"\/>//g' /dspace/config/item-submission.xml
        ls -lsah /dspace/webapps
        catalina.sh run
  # DSpace Solr container
  dspace7solr:
    container_name: dspace7solr
    # Uses official Solr image at https://hub.docker.com/_/solr/
    image: solr:8.11-slim
    networks:
      - dspacenet
    ports:
    - "127.0.0.1:8983:8983"
    stdin_open: true
    tty: true
    working_dir: /var/solr/data
    volumes:
      # Keep Solr data directory between reboots
      - solr_data:/var/solr/data
    entrypoint:
      - /bin/bash
      - '-c'
      - |
        init-var-solr
        precreate-core authority
        precreate-core oai
        precreate-core search
        precreate-core statistics
        exec solr -f
volumes:
  solr_data:
  m2:

networks:
  dspacenet:
    name: dspacenet
    driver: bridge